spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION}

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}